#Font-Family
forn_size                       12.0
font_family                     SchmakyFont NF Regular
italic_font                     SchmakyFont NF Italic
bold_font                       SchmakyFont NF Bold
bold_italic_font                SchmakyFont NF Bold Italic

#Cursor
cursor_stop_blinking_after      0
cursor_trail                    1

#Clipboard
strip_trailing_spaces           smart
copy_on_select                  yes

#Audio
enable_audio_bell               no

#Color
color0                          #010101
foreground                      #dddddd
background                      #000000
selection_foreground            #000000
selection_background            #FFFACD

#Window and Screen
background_blur                 0
background_opacity              0.8
window_padding_width            8
sync_to_monitor                 yes

#Shell and Terminal
shell                           /usr/bin/zsh
allow_remote_control            yes

# Mappings
map ctrl+tab                    no_op
map ctrl+shift+tab              no_op
map ctrl+shift+f                no_op
map ctrl+shift+h                no_op
